# ============================================================
# VISIONINSPECT AI
# DATA LOADER V2
# ============================================================
#
# Purpose:
#   Load leakage-safe manifests generated by split_v2.py.
#
# Features:
#   - Separate train / validation / test datasets
#   - Separate train / validation / test transforms
#   - Reproducible loading
#   - Class-balanced category training sampler
#   - Normal-only anomaly training support
#   - Supervised binary anomaly sampler support
#   - Dataset safety checks
#   - Image existence checks
#   - Sanity checks for category and anomaly loaders
#
# IMPORTANT:
#   Official test data is NEVER sampled into training.
#
# ============================================================

from __future__ import annotations

import json
import random
from pathlib import Path
from typing import Dict, List

import torch

from torch.utils.data import (
    DataLoader,
    WeightedRandomSampler,
)

from torchvision import transforms

from app.ai.dataset_v2 import (
    CategoryManifestDataset,
    AnomalyManifestDataset,
    BinaryManifestDataset,
)


# ============================================================
# CONFIGURATION
# ============================================================

SEED = 42

IMAGE_SIZE = 256

BATCH_SIZE = 32

NUM_WORKERS = 0


# ============================================================
# PATHS
# ============================================================

BASE_DIR = (
    Path(__file__)
    .resolve()
    .parent
)

MANIFEST_DIR = (
    BASE_DIR
    / "evaluation"
    / "manifests"
)

CATEGORY_MANIFEST = (
    MANIFEST_DIR
    / "category_manifest_v2.json"
)

ANOMALY_MANIFEST = (
    MANIFEST_DIR
    / "anomaly_manifest_v2.json"
)


# ============================================================
# REPRODUCIBILITY
# ============================================================

def create_generator():

    generator = torch.Generator()

    generator.manual_seed(
        SEED
    )

    return generator


def seed_worker(
    worker_id,
):

    worker_seed = (
        torch.initial_seed()
        % (2 ** 32)
    )

    random.seed(
        worker_seed
    )


# ============================================================
# TRANSFORMS
# ============================================================

# ------------------------------------------------------------
# TRAIN TRANSFORM
# ------------------------------------------------------------

TRAIN_TRANSFORM = transforms.Compose([

    transforms.Resize(
        (
            IMAGE_SIZE,
            IMAGE_SIZE,
        )
    ),

    transforms.RandomHorizontalFlip(
        p=0.5
    ),

    transforms.RandomRotation(
        degrees=8
    ),

    transforms.ColorJitter(
        brightness=0.10,
        contrast=0.10,
        saturation=0.05,
        hue=0.02,
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[
            0.485,
            0.456,
            0.406,
        ],
        std=[
            0.229,
            0.224,
            0.225,
        ],
    ),
])


# ------------------------------------------------------------
# VALIDATION TRANSFORM
# ------------------------------------------------------------

VAL_TRANSFORM = transforms.Compose([

    transforms.Resize(
        (
            IMAGE_SIZE,
            IMAGE_SIZE,
        )
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[
            0.485,
            0.456,
            0.406,
        ],
        std=[
            0.229,
            0.224,
            0.225,
        ],
    ),
])


# ------------------------------------------------------------
# TEST TRANSFORM
# ------------------------------------------------------------

TEST_TRANSFORM = VAL_TRANSFORM


# ============================================================
# MANIFEST LOADING
# ============================================================

def load_manifest(
    path: Path,
) -> Dict:

    if not path.exists():

        raise FileNotFoundError(
            f"Manifest not found:\n"
            f"{path}\n\n"
            "Run split_v2.py first."
        )

    with path.open(
        "r",
        encoding="utf-8",
    ) as file:

        return json.load(
            file
        )


# ============================================================
# DATA LEAKAGE SAFETY
# ============================================================

def verify_no_overlap(
    train: List[Dict],
    validation: List[Dict],
    test: List[Dict],
):

    train_paths = {
        item["image_path"]
        for item in train
    }

    validation_paths = {
        item["image_path"]
        for item in validation
    }

    test_paths = {
        item["image_path"]
        for item in test
    }

    # --------------------------------------------------------
    # TRAIN / VALIDATION
    # --------------------------------------------------------

    if (
        train_paths
        & validation_paths
    ):

        raise RuntimeError(
            "DATA LEAKAGE: "
            "train/validation overlap."
        )

    # --------------------------------------------------------
    # TRAIN / TEST
    # --------------------------------------------------------

    if (
        train_paths
        & test_paths
    ):

        raise RuntimeError(
            "DATA LEAKAGE: "
            "train/test overlap."
        )

    # --------------------------------------------------------
    # VALIDATION / TEST
    # --------------------------------------------------------

    if (
        validation_paths
        & test_paths
    ):

        raise RuntimeError(
            "DATA LEAKAGE: "
            "validation/test overlap."
        )


# ============================================================
# IMAGE EXISTENCE CHECK
# ============================================================

def verify_image_paths(
    samples: List[Dict],
):

    missing = []

    for sample in samples:

        path = Path(
            sample["image_path"]
        )

        if not path.exists():

            missing.append(
                str(path)
            )

    if missing:

        preview = (
            missing[:10]
        )

        raise FileNotFoundError(
            "Missing dataset images:\n"
            + "\n".join(
                preview
            )
        )


# ============================================================
# CATEGORY SAMPLER
# ============================================================

def create_category_sampler(
    samples: List[Dict],
):

    if not samples:

        raise RuntimeError(
            "Category training set "
            "is empty."
        )

    labels = [

        int(
            sample["category_index"]
        )

        for sample in samples
    ]

    # --------------------------------------------------------
    # COUNT SAMPLES PER CATEGORY
    # --------------------------------------------------------

    counts = {}

    for label in labels:

        counts[label] = (
            counts.get(
                label,
                0,
            )
            + 1
        )

    # --------------------------------------------------------
    # INVERSE-FREQUENCY WEIGHTS
    # --------------------------------------------------------

    weights = {

        label:
            1.0 / count

        for label, count
        in counts.items()
    }

    sample_weights = [

        weights[label]

        for label in labels
    ]

    return WeightedRandomSampler(

        weights=torch.DoubleTensor(
            sample_weights
        ),

        num_samples=len(
            sample_weights
        ),

        replacement=True,
    )


# ============================================================
# ANOMALY SAMPLER
# ============================================================

def create_anomaly_sampler(
    samples: List[Dict],
):
    """
    Create the anomaly training sampler.

    MVTec AD uses normal-only training images.

    Therefore:

        {0}       -> normal-only training
        {0, 1}    -> supervised binary training

    The official defective test images are NEVER added
    to the training sampler.
    """

    if not samples:

        raise RuntimeError(
            "Anomaly training set "
            "is empty."
        )

    # --------------------------------------------------------
    # READ LABELS
    # --------------------------------------------------------

    labels = [

        int(
            sample["label"]
        )

        for sample in samples
    ]

    unique_labels = set(
        labels
    )

    # --------------------------------------------------------
    # VALIDATE LABELS
    # --------------------------------------------------------

    if not unique_labels.issubset(
        {
            0,
            1,
        }
    ):

        raise ValueError(
            "Anomaly labels must "
            "be 0 or 1.\n"
            f"Received: "
            f"{sorted(unique_labels)}"
        )

    # --------------------------------------------------------
    # NORMAL-ONLY MVTec TRAINING
    # --------------------------------------------------------

    if unique_labels == {
        0
    }:

        print(
            "Anomaly training mode : "
            "NORMAL-ONLY"
        )

        print(
            "Anomaly sampler        : "
            "UNIFORM"
        )

        # Returning None tells DataLoader to use normal
        # shuffled sampling.
        return None

    # --------------------------------------------------------
    # SUPERVISED BINARY TRAINING
    # --------------------------------------------------------

    if unique_labels == {
        0,
        1,
    }:

        counts = {}

        for label in labels:

            counts[label] = (
                counts.get(
                    label,
                    0,
                )
                + 1
            )

        class_weights = {

            label:
                1.0 / count

            for label, count
            in counts.items()
        }

        sample_weights = [

            class_weights[label]

            for label in labels
        ]

        print(
            "Anomaly training mode : "
            "SUPERVISED BINARY"
        )

        print(
            "Anomaly sampler        : "
            "BALANCED"
        )

        return WeightedRandomSampler(

            weights=torch.DoubleTensor(
                sample_weights
            ),

            num_samples=len(
                sample_weights
            ),

            replacement=True,
        )

    raise RuntimeError(
        "Unsupported anomaly "
        "label distribution."
    )


# ============================================================
# CATEGORY DATA LOADERS
# ============================================================

def get_category_dataloaders(
    batch_size=BATCH_SIZE,
):

    manifest = load_manifest(
        CATEGORY_MANIFEST
    )

    # --------------------------------------------------------
    # SPLITS
    # --------------------------------------------------------

    train_samples = manifest.get(
        "train",
        []
    )

    validation_samples = (
        manifest.get(
            "validation",
            []
        )
    )

    test_samples = manifest.get(
        "test",
        []
    )

    # --------------------------------------------------------
    # SAFETY
    # --------------------------------------------------------

    verify_no_overlap(
        train_samples,
        validation_samples,
        test_samples,
    )

    verify_image_paths(
        train_samples
        + validation_samples
        + test_samples
    )

    # --------------------------------------------------------
    # DATASETS
    # --------------------------------------------------------

    train_dataset = (
        CategoryManifestDataset(
            train_samples,
            TRAIN_TRANSFORM,
        )
    )

    validation_dataset = (
        CategoryManifestDataset(
            validation_samples,
            VAL_TRANSFORM,
        )
    )

    test_dataset = (
        CategoryManifestDataset(
            test_samples,
            TEST_TRANSFORM,
        )
    )

    # --------------------------------------------------------
    # CATEGORY SAMPLER
    # --------------------------------------------------------

    sampler = (
        create_category_sampler(
            train_samples
        )
    )

    # --------------------------------------------------------
    # TRAIN LOADER
    # --------------------------------------------------------

    train_loader = DataLoader(

        train_dataset,

        batch_size=batch_size,

        sampler=sampler,

        num_workers=NUM_WORKERS,

        pin_memory=(
            torch.cuda.is_available()
        ),

        worker_init_fn=seed_worker,

        generator=create_generator(),
    )

    # --------------------------------------------------------
    # VALIDATION LOADER
    # --------------------------------------------------------

    validation_loader = DataLoader(

        validation_dataset,

        batch_size=batch_size,

        shuffle=False,

        num_workers=NUM_WORKERS,

        pin_memory=(
            torch.cuda.is_available()
        ),
    )

    # --------------------------------------------------------
    # TEST LOADER
    # --------------------------------------------------------

    test_loader = DataLoader(

        test_dataset,

        batch_size=batch_size,

        shuffle=False,

        num_workers=NUM_WORKERS,

        pin_memory=(
            torch.cuda.is_available()
        ),
    )

    # --------------------------------------------------------
    # INFORMATION
    # --------------------------------------------------------

    print()

    print(
        "=" * 70
    )

    print(
        "VISIONINSPECT AI - "
        "CATEGORY DATALOADER V2"
    )

    print(
        "=" * 70
    )

    print(
        f"Training samples   : "
        f"{len(train_dataset)}"
    )

    print(
        f"Validation samples : "
        f"{len(validation_dataset)}"
    )

    print(
        f"Official test      : "
        f"{len(test_dataset)}"
    )

    print(
        f"Batch size         : "
        f"{batch_size}"
    )

    print(
        "Balanced sampler   : ENABLED"
    )

    print(
        "=" * 70
    )

    return (
        train_loader,
        validation_loader,
        test_loader,
    )


# ============================================================
# ANOMALY DATA LOADERS
# ============================================================

def get_anomaly_dataloaders(
    batch_size=BATCH_SIZE,
):

    manifest = load_manifest(
        ANOMALY_MANIFEST
    )

    # --------------------------------------------------------
    # SPLITS
    # --------------------------------------------------------

    train_samples = manifest.get(
        "train",
        []
    )

    validation_samples = (
        manifest.get(
            "validation",
            []
        )
    )

    test_samples = manifest.get(
        "test",
        []
    )

    # --------------------------------------------------------
    # SAFETY
    # --------------------------------------------------------

    verify_no_overlap(
        train_samples,
        validation_samples,
        test_samples,
    )

    verify_image_paths(
        train_samples
        + validation_samples
        + test_samples
    )

    # --------------------------------------------------------
    # DATASETS
    # --------------------------------------------------------

    train_dataset = (
        AnomalyManifestDataset(
            train_samples,
            TRAIN_TRANSFORM,
        )
    )

    validation_dataset = (
        AnomalyManifestDataset(
            validation_samples,
            VAL_TRANSFORM,
        )
    )

    test_dataset = (
        AnomalyManifestDataset(
            test_samples,
            TEST_TRANSFORM,
        )
    )

    # --------------------------------------------------------
    # ANOMALY SAMPLER
    # --------------------------------------------------------

    sampler = (
        create_anomaly_sampler(
            train_samples
        )
    )

    # --------------------------------------------------------
    # TRAIN LOADER
    # --------------------------------------------------------
    #
    # If MVTec training is normal-only:
    #
    #     sampler = None
    #
    # We use shuffle=True.
    #
    # If a genuine supervised binary dataset is used:
    #
    #     sampler = WeightedRandomSampler
    #
    # --------------------------------------------------------

    if sampler is None:

        train_loader = DataLoader(

            train_dataset,

            batch_size=batch_size,

            shuffle=True,

            num_workers=NUM_WORKERS,

            pin_memory=(
                torch.cuda.is_available()
            ),

            worker_init_fn=seed_worker,

            generator=create_generator(),
        )

    else:

        train_loader = DataLoader(

            train_dataset,

            batch_size=batch_size,

            sampler=sampler,

            num_workers=NUM_WORKERS,

            pin_memory=(
                torch.cuda.is_available()
            ),

            worker_init_fn=seed_worker,

            generator=create_generator(),
        )

    # --------------------------------------------------------
    # VALIDATION LOADER
    # --------------------------------------------------------

    validation_loader = DataLoader(

        validation_dataset,

        batch_size=batch_size,

        shuffle=False,

        num_workers=NUM_WORKERS,

        pin_memory=(
            torch.cuda.is_available()
        ),
    )

    # --------------------------------------------------------
    # TEST LOADER
    # --------------------------------------------------------

    test_loader = DataLoader(

        test_dataset,

        batch_size=batch_size,

        shuffle=False,

        num_workers=NUM_WORKERS,

        pin_memory=(
            torch.cuda.is_available()
        ),
    )

    # --------------------------------------------------------
    # INFORMATION
    # --------------------------------------------------------

    print()

    print(
        "=" * 70
    )

    print(
        "VISIONINSPECT AI - "
        "ANOMALY DATALOADER V2"
    )

    print(
        "=" * 70
    )

    print(
        f"Training samples   : "
        f"{len(train_dataset)}"
    )

    print(
        f"Validation samples : "
        f"{len(validation_dataset)}"
    )

    print(
        f"Official test      : "
        f"{len(test_dataset)}"
    )

    print(
        f"Batch size         : "
        f"{batch_size}"
    )

    print(
        "=" * 70
    )

    return (
        train_loader,
        validation_loader,
        test_loader,
    )


# ============================================================
# CATEGORY SANITY CHECK
# ============================================================

def sanity_check_category():

    print()

    print(
        "=" * 70
    )

    print(
        "RUNNING CATEGORY LOADER SANITY CHECK"
    )

    print(
        "=" * 70
    )

    (
        train_loader,
        validation_loader,
        test_loader,
    ) = get_category_dataloaders(
        batch_size=4
    )

    # --------------------------------------------------------
    # TRAIN BATCH
    # --------------------------------------------------------

    train_batch = next(
        iter(train_loader)
    )

    # --------------------------------------------------------
    # VALIDATION BATCH
    # --------------------------------------------------------

    validation_batch = next(
        iter(validation_loader)
    )

    # --------------------------------------------------------
    # TEST BATCH
    # --------------------------------------------------------

    test_batch = next(
        iter(test_loader)
    )

    # --------------------------------------------------------
    # TRAIN
    # --------------------------------------------------------

    train_images = (
        train_batch["image"]
    )

    train_labels = (
        train_batch["label"]
    )

    # --------------------------------------------------------
    # VALIDATION
    # --------------------------------------------------------

    validation_images = (
        validation_batch["image"]
    )

    validation_labels = (
        validation_batch["label"]
    )

    # --------------------------------------------------------
    # TEST
    # --------------------------------------------------------

    test_images = (
        test_batch["image"]
    )

    test_labels = (
        test_batch["label"]
    )

    # --------------------------------------------------------
    # OUTPUT
    # --------------------------------------------------------

    print()

    print(
        "CATEGORY TRAIN BATCH"
    )

    print(
        f"Image shape : "
        f"{tuple(train_images.shape)}"
    )

    print(
        f"Label shape : "
        f"{tuple(train_labels.shape)}"
    )

    print(
        f"Image dtype : "
        f"{train_images.dtype}"
    )

    print(
        f"Label dtype : "
        f"{train_labels.dtype}"
    )

    print(
        f"Labels      : "
        f"{train_labels.tolist()}"
    )

    print()

    print(
        "CATEGORY VALIDATION BATCH"
    )

    print(
        f"Image shape : "
        f"{tuple(validation_images.shape)}"
    )

    print(
        f"Label shape : "
        f"{tuple(validation_labels.shape)}"
    )

    print()

    print(
        "CATEGORY TEST BATCH"
    )

    print(
        f"Image shape : "
        f"{tuple(test_images.shape)}"
    )

    print(
        f"Label shape : "
        f"{tuple(test_labels.shape)}"
    )

    # --------------------------------------------------------
    # ASSERTIONS
    # --------------------------------------------------------

    assert train_images.shape == (
        4,
        3,
        IMAGE_SIZE,
        IMAGE_SIZE,
    )

    assert train_labels.shape == (
        4,
    )

    assert train_images.dtype == (
        torch.float32
    )

    assert train_labels.dtype == (
        torch.int64
    )

    assert torch.all(
        train_labels >= 0
    )

    assert torch.all(
        train_labels < 15
    )

    print()

    print(
        "Category loader sanity check: PASS"
    )

    print(
        "=" * 70
    )


# ============================================================
# ANOMALY SANITY CHECK
# ============================================================

def sanity_check_anomaly():

    print()

    print(
        "=" * 70
    )

    print(
        "RUNNING ANOMALY LOADER SANITY CHECK"
    )

    print(
        "=" * 70
    )

    (
        train_loader,
        validation_loader,
        test_loader,
    ) = get_anomaly_dataloaders(
        batch_size=4
    )

    # --------------------------------------------------------
    # TRAIN BATCH
    # --------------------------------------------------------

    batch = next(
        iter(train_loader)
    )

    images = (
        batch["image"]
    )

    labels = (
        batch["label"]
    )

    # --------------------------------------------------------
    # OUTPUT
    # --------------------------------------------------------

    print()

    print(
        "ANOMALY TRAIN BATCH"
    )

    print(
        f"Image shape : "
        f"{tuple(images.shape)}"
    )

    print(
        f"Label shape : "
        f"{tuple(labels.shape)}"
    )

    print(
        f"Image dtype : "
        f"{images.dtype}"
    )

    print(
        f"Label dtype : "
        f"{labels.dtype}"
    )

    print(
        f"Labels      : "
        f"{labels.tolist()}"
    )

    # --------------------------------------------------------
    # ASSERTIONS
    # --------------------------------------------------------

    assert images.shape == (
        4,
        3,
        IMAGE_SIZE,
        IMAGE_SIZE,
    )

    assert labels.shape == (
        4,
    )

    assert labels.dtype == (
        torch.int64
    )

    assert torch.all(
        (labels == 0)
        | (labels == 1)
    )

    print()

    print(
        "Anomaly loader sanity check: PASS"
    )

    print(
        "=" * 70
    )


# ============================================================
# ALL SANITY CHECKS
# ============================================================

def run_all_sanity_checks():

    print()

    print(
        "#" * 70
    )

    print(
        "VISIONINSPECT AI"
    )

    print(
        "DATA LOADER V2 SANITY TEST"
    )

    print(
        "#" * 70
    )

    # --------------------------------------------------------
    # CATEGORY
    # --------------------------------------------------------

    sanity_check_category()

    # --------------------------------------------------------
    # ANOMALY
    # --------------------------------------------------------

    sanity_check_anomaly()

    # --------------------------------------------------------
    # COMPLETE
    # --------------------------------------------------------

    print()

    print(
        "#" * 70
    )

    print(
        "ALL DATA LOADER V2 SANITY CHECKS PASSED"
    )

    print(
        "#" * 70
    )

    print()


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":

    run_all_sanity_checks()