import Modal from "../common/Modal";

export default function InspectionDetailsModal({
  open,
  onClose,
  inspection,
}) {
  if (!inspection) return null;

  const quality = inspection.image_quality;

  // ---------------------------------------------------------
  // Quality status styling
  // ---------------------------------------------------------

  const getQualityStatusClass = (status) => {
    switch (status) {
      case "Good":
        return "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20";

      case "Acceptable":
        return "bg-yellow-500/10 text-yellow-400 border border-yellow-500/20";

      case "Poor":
        return "bg-red-500/10 text-red-400 border border-red-500/20";

      default:
        return "bg-slate-500/10 text-slate-400 border border-slate-500/20";
    }
  };

  // ---------------------------------------------------------
  // Quality score color
  // ---------------------------------------------------------

  const getQualityScoreClass = (score) => {
    if (score >= 80) {
      return "text-emerald-400";
    }

    if (score >= 60) {
      return "text-yellow-400";
    }

    return "text-red-400";
  };

  return (
    <Modal
      open={open}
      onClose={onClose}
      title="Inspection Details"
      footer={
        <button
          onClick={onClose}
          className="rounded-lg bg-cyan-600 px-5 py-2 text-white hover:bg-cyan-700 transition-colors"
        >
          Close
        </button>
      }
    >
      <div className="space-y-6">

        {/* =====================================================
            SECTION 1 — INSPECTION IMAGES
        ===================================================== */}

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">

          {/* Uploaded Image */}

          <div>
            <h4 className="mb-3 font-semibold text-slate-300">
              Uploaded Image
            </h4>

            {inspection.image_url ? (
              <img
                src={inspection.image_url}
                alt="Uploaded inspection"
                className="w-full rounded-xl border border-slate-700 object-contain"
              />
            ) : (
              <div className="flex min-h-[200px] items-center justify-center rounded-xl border border-slate-700 text-slate-500">
                Image not available
              </div>
            )}
          </div>


          {/* AI Detection Result */}

          <div>
            <h4 className="mb-3 font-semibold text-slate-300">
              AI Detection Result
            </h4>

            {inspection.result_image_url ? (
              <img
                src={inspection.result_image_url}
                alt="AI detection result"
                className="w-full rounded-xl border border-slate-700 object-contain"
              />
            ) : (
              <div className="flex min-h-[200px] items-center justify-center rounded-xl border border-slate-700 text-slate-500">
                No result image available
              </div>
            )}
          </div>

        </div>


        <div>

          <div className="mb-4">

            <h3 className="text-lg font-semibold text-white">
              🤖 AI Inspection Result
            </h3>

            <p className="mt-1 text-sm text-slate-400">
              Defect detection and severity assessment generated by the AI model.
            </p>

          </div>


          <div className="grid grid-cols-2 gap-5">

            <Detail
              label="Product"
              value={inspection.product_name || "N/A"}
            />

            <Detail
              label="Status"
              value={
                inspection.status
                  ? inspection.status.toUpperCase()
                  : "N/A"
              }
            />

            <Detail
              label="Defect Type"
              value={
                inspection.defect_type || "No Defect"
              }
            />

            <Detail
              label="Confidence"
              value={
                inspection.confidence != null
                  ? `${(
                      inspection.confidence * 100
                    ).toFixed(2)} %`
                  : "N/A"
              }
            />

            <Detail
              label="Severity"
              value={
                inspection.severity || "None"
              }
            />

            <Detail
              label="Severity Score"
              value={`${inspection.severity_score ?? 0}/100`}
            />

            <Detail
              label="Recommendation"
              value={
                inspection.recommendation || "N/A"
              }
            />

            <Detail
              label="Processing Time"
              value={
                inspection.processing_time != null
                  ? `${inspection.processing_time} sec`
                  : "N/A"
              }
            />

            <Detail
              label="Inspection Date"
              value={
                inspection.created_at
                  ? new Date(
                      inspection.created_at
                    ).toLocaleString()
                  : "N/A"
              }
            />

          </div>

        </div>

      </div>
    </Modal>
  );
}


/* =========================================================
   STANDARD INSPECTION DETAIL
========================================================= */

function Detail({
  label,
  value,
}) {
  return (
    <div className="rounded-xl border border-slate-700 bg-slate-900/40 p-4">

      <p className="text-sm text-slate-400">
        {label}
      </p>

      <h3 className="mt-2 font-semibold leading-6 text-white">
        {value}
      </h3>

    </div>
  );
}


/* =========================================================
   IMAGE QUALITY DETAIL
========================================================= */

function QualityDetail({
  label,
  value,
}) {
  return (
    <div className="rounded-xl border border-slate-700 bg-slate-950/30 p-4">

      <p className="text-xs text-slate-500">
        {label}
      </p>

      <p className="mt-1 font-semibold text-slate-200">
        {value ?? "N/A"}
      </p>

    </div>
  );
}


/* =========================================================
   QUALITY INDICATOR
========================================================= */

function QualityIndicator({
  label,
  value,
  good,
}) {
  return (
    <div className="rounded-xl border border-slate-700 bg-slate-950/30 p-4">

      <div className="flex items-center justify-between">

        <p className="text-sm text-slate-400">
          {label}
        </p>

        <span
          className={`text-lg ${
            good
              ? "text-emerald-400"
              : "text-red-400"
          }`}
        >
          {good ? "✓" : "⚠"}
        </span>

      </div>

      <p className="mt-2 text-sm font-semibold text-slate-200">
        {value ?? "N/A"}
      </p>

      <p
        className={`mt-1 text-xs ${
          good
            ? "text-emerald-400"
            : "text-red-400"
        }`}
      >
        {good ? "Good" : "Needs Improvement"}
      </p>

    </div>
  );
}