function InspectionReports() {
  return (
    <div className="page-container">
      <h1>📄 Inspection Reports</h1>
      <p>View all inspection reports generated by the AI system.</p>

      <table
  style={{
    width: "100%",
    borderCollapse: "collapse",
    marginTop: "30px",
    color: "white",
    textAlign: "center",
  }}
>
  <thead style={{ background: "#2563eb" }}>
    <tr>
      <th style={{ padding: "15px" }}>Report ID</th>
      <th style={{ padding: "15px" }}>Product</th>
      <th style={{ padding: "15px" }}>Result</th>
      <th style={{ padding: "15px" }}>Date</th>
    </tr>
  </thead>

  <tbody>
    <tr style={{ background: "#0f172a" }}>
      <td style={{ padding: "15px" }}>R001</td>
      <td style={{ padding: "15px" }}>Bottle</td>
      <td style={{ padding: "15px", color: "#22c55e", fontWeight: "bold" }}>
        PASS
      </td>
      <td style={{ padding: "15px" }}>30-07-2026</td>
    </tr>

    <tr style={{ background: "#111827" }}>
      <td style={{ padding: "15px" }}>R002</td>
      <td style={{ padding: "15px" }}>Cable</td>
      <td style={{ padding: "15px", color: "#ef4444", fontWeight: "bold" }}>
        FAIL
      </td>
      <td style={{ padding: "15px" }}>30-07-2026</td>
    </tr>

    <tr style={{ background: "#0f172a" }}>
      <td style={{ padding: "15px" }}>R003</td>
      <td style={{ padding: "15px" }}>Metal Nut</td>
      <td style={{ padding: "15px", color: "#22c55e", fontWeight: "bold" }}>
        PASS
      </td>
      <td style={{ padding: "15px" }}>30-07-2026</td>
    </tr>
  </tbody>
</table>
    </div>
  );
}

export default InspectionReports;